name: build-scrapper

#on:
#  push:
#    paths:
#      - 'JavaService/scrapper/**'
#  branches:
#    - hw9
#
#  pull_request:
#    paths:
#      - 'JavaService/scrapper/**'

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Maven Package
        run: mvn package -pl scrapper -am