springdoc:
  swagger-ui:
    path: /swagger-ui

app:
  test: test_key_spring_13qk2kw!
  scheduler:
    interval: 50000
  database-access-type: jpa

server:
  port: 8077

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/migrations/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password