springdoc:
  swagger-ui:
    path: /swagger-ui

app:
  test: test_key_spring_13qk2kw!
  scheduler:
    interval: 10000

server:
  port: 8077

spring:
  liquibase:
    change-log: classpath*:db/migrations/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password