name: build-bot

on:
  push:
    paths:
      - 'JavaService/bot/**'

  pull_request:
    paths:
      - 'JavaService/bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - run: cd .\JavaService\
      - name: Maven Package
        run: mvn package -pl bot -am