name: build-bot

on:
  push:
    paths:
      - 'JavaService/bot/**'
      - 'JavaService/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Maven Package
        run: cd ./JavaService && mvn package -pl bot -am
      - name: Docker Build
        run: docker build -t test_name . -f JavaService/bot/Dockerfile
      - name: test
        run: ls