name: build-scrapper

on:
  push:
    paths:
      - 'JavaService/scrapper/**'

  pull_request:
    paths:
      - 'JavaService/scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - run: ls JavaService
      - run: cd ./JavaService
      - run: ls
      - name: Maven Package
        run: cd ./JavaService && mvn package -pl scrapper -am