name: build-scrapper

on:
  push:
    paths:
      - 'JavaService/scrapper/**'
      - 'JavaService/link-parser/**'
      - 'JavaService/pom.xml'
      - 'JavaService/scrapper-jooq/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Maven Package
        run: cd ./JavaService && mvn package -pl scrapper -am
      - name: Docker Build
        run: docker build -t test_name . -f JavaService/scrapper/Dockerfile
      - name: test
        run: ls