name: build-scrapper

on:
  push:
    paths:
      - 'JavaService/scrapper/**'
      - 'JavaService/link-parser/**'
      - 'JavaService/pom.xml'
      - 'JavaService/scrapper-jooq/**'
      - '.github/workflows/scrapper.yml'
env:
  REGISTRY: ghcr.io
  USERNAME: drakon-top

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Maven Package
        run: cd ./JavaService && mvn package -pl scrapper -am
      - name: Docker Build
        run: docker build -t $REGISTRY/$USERNAME/scrapper:latest . -f JavaService/scrapper/Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push
        run: docker push $REGISTRY/$USERNAME/scrapper:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run checks
        run: cd ./JavaService && mvn -pl scrapper -am checkstyle:check